### ISSUE TITLE
可以支持pdf矢量瓦片吗

### ISSUE THREAD

**Issue by liyihongcug** [MikesWei/CesiumVectorTile#13]
如何支持pdf矢量瓦片吗

**Comment by MikesWei** [comment]
没有接触过这个格式的矢量，不知道这个是瓦片的格式，还是矢量文件格式。如果已经是瓦片了，请自己实现一个ImageryProvider来直接加载这种瓦片数据然后需要渲染的话，使用canvas技术渲染成图片返回给cesium即可。

**Comment by liyihongcug** [comment]
已经搞定。 这个是LOD 
ol.format.MVT();  瓦片 requestImage
