### ISSUE TITLE
使用cesium1.5.3版本报错

### ISSUE THREAD

**Issue by xujunpro2** [MikesWei/CesiumVectorTile#2]
在构建VectorTileImageryProvider出现异常

**Comment by MikesWei** [comment]
构建过程并没有依赖Cesium。您确定使用旧版本构建成功过吗

**Comment by xujunpro2** [comment]
new VectorTileImageryProvider()出错了，我直接使用你项目的demo测试的，用你提供的cesium.js是可以运行的，换最新的cesium1.5.3的cesium.js无法运行

**Comment by MikesWei** [comment]
那天你提完问题，我后来直接clone到本地，换了1.53的Cesium，测试了没发现你说的问题呢。现在的版本thirdparty里的cesium就是1.53的，你可以再试试

**Comment by MikesWei** [comment]
对了，最好能贴出报错的信息来，以便确定问题原因

**Comment by xujunpro2** [comment]
hi ! 已经可以了，效果不错！有点像openlayers的矢量图层切片的感觉。想请教个问题，我想在cesium上叠加一个geojson图层，但有个要求，就是在叠加之后还需要做个蒙版处理，就是类似裁边的那种处理。以前我用openlayers的时候，openlayers会在每个layer渲染结束之后提供一个回调函数：layer.on('precompose', function(event) {}）； 这个event包含一个canvas对象，我就可以用这个canvas做个clip()处理从而实现对图层的裁边，请教在cesium中该如何实现呢？
